import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../app/globals.css";
import AdminHeader from "../../Componant/AdminHeader/AdminHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hindustan Tims",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AdminHeader />
        {children}
      </body>
    </html>
  );
}
